apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: frontend-cpu-saturation
  namespace: default
spec:
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: frontend
  stressors:
    cpu:
      workers: 1
      load: 95
  duration: "10m"
