apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: default
  labels:
    app: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cartservice
      annotations:
        herald.dev/scenario: crashloop-cartservice-bad-deploy
    spec:
      serviceAccountName: cartservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.5
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_ADDR
              value: redis-cart:6379
          command:
            - /herald-intentional-crash
          ports:
            - containerPort: 7070
              protocol: TCP
          livenessProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
